version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./vectorizer/up.sql:/docker-entrypoint-initdb.d/up.sql
    env_file:
      - .env
    ports:
      - '5432:5432'

  vector-db:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.21.2
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - ./server:/server
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres-db
      - vector-db

  vectorizer:
    build:
      context: ./vectorizer
      dockerfile: Dockerfile
    container_name: vectorizer
    env_file:
      - .env
    depends_on:
      - postgres-db
      - vector-db
      - server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - server

volumes:
  postgres_data:
  weaviate_data:
